Debug `parallel` exiting properly

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -153,11 +153,11 @@ parent-vars:
   - echo "Data will be written to $REDIS_SIZES_KEY"
   - set -e
   - for example in ${INK_EXAMPLES_PATH}/*/; do
-      echo "./.scripts/build-contract.sh ${example} | 
+      echo "set -o pipefail; ./.scripts/build-contract.sh ${example} |
       redis-cli -u ${GITLAB_REDIS_URI} -x rpush ${REDIS_SIZES_KEY}" >> /tmp/cmds;
     done
   - for contract in ${DELEGATOR_SUBCONTRACTS}; do
-      echo "./.scripts/build-contract.sh ${INK_EXAMPLES_PATH}/delegator/${contract} | 
+      echo "set -o pipefail; ./.scripts/build-contract.sh ${INK_EXAMPLES_PATH}/delegator/${contract} |
       redis-cli -u ${GITLAB_REDIS_URI} -x rpush ${REDIS_SIZES_KEY}" >> /tmp/cmds;
     done
   - echo /tmp/cmds && cat /tmp/cmds
